In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings('ignore')

In [7]:
df = sns.load_dataset('iris')

In [8]:
df.head()

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [9]:
df['species'].value_counts()

,count
species,
setosa,50
versicolor,50
virginica,50


In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X = df.drop('species', axis=1)
y = df['species']

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.5, random_state=42)

In [13]:
from sklearn.neighbors import KNeighborsClassifier

In [14]:
model_knn = KNeighborsClassifier(n_neighbors=1)

In [15]:
model_knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=1)

In [16]:
round(model_knn.score(X_train, y_train)*100,2)

100.0

In [17]:
from sklearn.svm import SVC

In [18]:
model_SVM = SVC(gamma='auto')

In [19]:
model_SVM.fit(X_train, y_train)

SVC(gamma='auto')

In [20]:
round(model_knn.score(X_train, y_train)*100,2)

100.0

In [21]:
from sklearn.model_selection import RandomizedSearchCV

In [22]:
classifier = RandomizedSearchCV(model_SVM, {
    'C': [1,10,20],
    'kernel': ['rbf','linear']
}, cv=5, return_train_score=False, n_iter=4)

In [23]:
classifier.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=4,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [24]:
classifier.cv_results_

{'mean_fit_time': array([0.00230675, 0.00155935, 0.00168829, 0.00151687]),
 'std_fit_time': array([7.00625688e-04, 5.01483543e-05, 3.13672761e-04, 8.43728824e-05]),
 'mean_score_time': array([0.00150595, 0.00115318, 0.00117421, 0.00117097]),
 'std_score_time': array([2.60622223e-04, 2.23841401e-05, 4.70085022e-05, 4.74069671e-05]),
 'param_kernel': masked_array(data=['linear', 'rbf', 'rbf', 'rbf'],
              mask=[False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'param_C': masked_array(data=[10, 10, 1, 20],
              mask=[False, False, False, False],
        fill_value=999999),
 'params': [{'kernel': 'linear', 'C': 10},
  {'kernel': 'rbf', 'C': 10},
  {'kernel': 'rbf', 'C': 1},
  {'kernel': 'rbf', 'C': 20}],
 'split0_test_score': array([1.        , 0.96666667, 0.96666667, 0.96666667]),
 'split1_test_score': array([1., 1., 1., 1.]),
 'split2_test_score': array([0.9       , 0.96666667, 0.96666667, 0.9       ]),
 'split3_test_score': arra

In [25]:
results = pd.DataFrame(classifier.cv_results_)

In [31]:
results[['param_C','param_kernel','mean_test_score']]

,param_C,param_kernel,mean_test_score
0,10,linear,0.973333
1,10,rbf,0.980000
2,1,rbf,0.980000
3,20,rbf,0.966667


In [33]:
best_score = classifier.best_score_
best_model = classifier.best_estimator_

In [34]:
y_pred_svm = best_model.predict(X_test)

In [36]:
from sklearn.metrics import accuracy_score

test_accuracy = accuracy_score(y_test, y_pred_svm)

print("Best CV Score:", best_score)
print("Unseen Test Accuracy:", test_accuracy)

Best CV Score: 0.9800000000000001
Unseen Test Accuracy: 1.0


In [38]:
from sklearn.metrics import classification_report, confusion_matrix

print(confusion_matrix(y_test, y_pred_svm))
print(classification_report(y_test, y_pred_svm))

[[29  0  0]
 [ 0 23  0]
 [ 0  0 23]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        29
  versicolor       1.00      1.00      1.00        23
   virginica       1.00      1.00      1.00        23

    accuracy                           1.00        75
   macro avg       1.00      1.00      1.00        75
weighted avg       1.00      1.00      1.00        75

