In [13]:
import numpy as np 

arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [17]:
stringList = [1,2,3.4, "harry"]
np.array(stringList) 

array(['1', '2', '3.4', 'harry'], dtype='<U32')

In [18]:
floatList = [1,2,4.5,3,6]
np.array(floatList)

array([1. , 2. , 4.5, 3. , 6. ])

In [19]:
numberList = [1,2,3,4,5,6,7]
np.array(numberList)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Vector example:

In [20]:
vectorExample = [1,2,3,4,5]
np.array(vectorExample)

array([1, 2, 3, 4, 5])

In [ ]:
# Matrix: 

In [32]:
np.array([
    [1,2,3],
    ["harsh" , "sheharyar" , "kaise ho"], 
    [1.1 , 2.2 , 3.3]
])

array([['1', '2', '3'],
       ['harsh', 'sheharyar', 'kaise ho'],
       ['1.1', '2.2', '3.3']], dtype='<U32')

In [34]:
l = [[1,2,3] , [4,5,6] , [7,8,9]]

np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Array generation function:

In [ ]:
# Vector array generation:

In [44]:
arrGen = np.arange(1,11)
arrGen

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arrZeros = np.zeros(6 , dtype=int)
arrZeros

array([0, 0, 0, 0, 0, 0])

In [ ]:
# Matrix array generation:

In [58]:
arrZerosMatrix = np.zeros((3,8) , dtype= int)
arrZerosMatrix

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [57]:
arrOnesMatrix = np.ones((3,3) , dtype=int)
arrOnesMatrix

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Lin(Linear) space in Array:

In [2]:
n = int(input("Enter the number whose table you want: "))
nMul10 = n * 10
arrLinSpace = np.linspace(n , nMul10 , 10 , dtype=int)
arrLinSpace

ValueError: invalid literal for int() with base 10: ''

In [ ]:
arrExperiment1 = np.linspace(1,10,10 , dtype=int)
arrExperiment1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
arrExperiment2 = np.linspace(10,1,10 , dtype=int)
arrExperiment2

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [ ]:
n = int(input("Enter your number trough which you want 10 more above powers"))

i = 1
while i <= 10 :
    print(n * i) 
    i += 1

In [ ]:
# //Array Attributes:

In [139]:
arrAttribute = np.array([[1,2,3],[4,5,6],[7,8,9]])
arrAttribute.shape

(3, 3)

In [140]:
arrAttribute.size

9

In [141]:
arrAttribute.dtype

dtype('int64')

In [ ]:
# // Array Methods:

In [145]:
arrMethod = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

In [146]:
arrMethod.min()

np.int64(1)

In [147]:
arrMethod.max()

np.int64(12)

In [148]:
arrMethod.sum()

np.int64(78)

In [153]:
arrSum = np.array([
    [1,2,3] ,
    [4,5,6] ,
    [7,8,9]
])

In [158]:
arrColumnSum = np.sum(arrSum , axis=0)
arrColumnSum

array([12, 15, 18])

In [160]:
arrRowSum = np.sum(arrSum , axis=1)
arrRowSum

array([ 6, 15, 24])

In [165]:
arrSum.mean()

np.float64(5.0)

In [168]:
arrStandardDeviation = arr.std()

int(arrStandardDeviation)
arrStandardDeviation

np.float64(1.4142135623730951)

In [170]:
arrMaxArg = arrSum.argmax()
arrMaxArg

np.int64(8)

In [171]:
arrMinArg = arrSum.argmin()
arrMinArg

np.int64(0)

In [174]:
arrTo30 = np.arange(1,31)
arrTo30

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [184]:
arrTo30 = arrTo30.reshape(3,10)
arrTo30

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [ ]:
# # 


# # // difference between python lists and numpy arrays:

# # // Features             Python list    NumpyArrays
# # //////////////////////////////////////////////////
# #    Data types           Mixed allowed     Same data type only
# #    Peformance           Slower            Much faster(C-like)
# #    Memory efficiency    low               high
# #    Vectors operations   Manual loops      Easy + Features


# # // What are we going to do in arrays section:


# # // Basic Array Creation

# # // Array generation function

# # // Random generation function

# # // Array Attributes

# # // Array Methods

# # // Reshaping and resizing

# list = [1,2,3.4, "harry"]
# np.array(list) #// now everything will be converted into string because you give one string in a  list

# floatList = [1,2,4.5,3,6]
# np.array(floatList) #// now everything will be converted into string because you give one float in a  list


# numberList = [1,2,3,4,5,6,7]
# np.array(numberList) #// now everything will be converted into number because you give all number in a  list


# // Difference between verctors and matrix:

# // Vectors are something which are creates in one single dimensional space. Vectors consists of single row

# // For example:
# // [1,2,3,4,5]

# // Matrix are something which are creates in one two dimensional space. Matrix consists of multiple rows and column. 2 dimensional have tensors.

# // For example:
# // [[1,2,3,4] , [5,6,7,8,9] , [10,11,12,13,14,15]]


# // What are rows and column in matrix:

# // if i say np.zeros((6,6) , dtype=int), the first 6 means 6 rows and and the second 6 means 6 column:
# // Simple rule: first value = no. of rows and second value = no. of column

# // Lin space:

# // It creates numbers evenly spaced between a start and an end value.
# // Simple formula: np.linspace(start, stop, number_of_values)


# // Random Generated Function:

# // In random module there's a concept of normalization in which in the random values will generate in between 0 to 1 and Standadization in which values will generate in between 3 to -3.

# // Normalization Example: 
# // np.random.rand(5)

# // Standadization Example: 
# // np.random.randn(10)


# // Array Attributes:

# // In NumPy, array attributes are properties that describe a NumPy array—like its shape, size, type, and memory layout. They are very important in AI because models constantly check the shape and structure of data.

# // Example:

# // arrAttribute = np.array([[1,2,3],[4,5,6],[7,8,9]])

#    arrAttribute.shape // output: (3, 3)

#    arrAttribute.size // output: 9

#    arrAttribute.dtype // output: dtype('int64')

# // Array Method:

# // An array method is a function that belongs to a NumPy array and is used to perform operations on it.

# // Example:

# // arrMethod = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])

# // arrMethod.min() // output: np.int64(1)

# // arrMethod.max() // np.int64(12)

# // arrMethod.sum() // np.int64(78)

# // np.sum(arrMethod , axis=0) // This will provide the column wise summation
# // np.sum(arrMethod , axis=1) // This will provide the row wise summation.

# // Simple rule: column wise sum = axis=0 , row wise sum = axis=1

# // arrSum.mean() // This will find the middle element from array:

# // for example: 

# // arrSum = np.array([
#     [1,2,3] ,
#     [4,5,6] ,
#     [7,8,9]
#    ])

# // arrSum.mean() // output: np.float64(5.0)


# arrSum.std() // STD stand for Standard Deviation

# // arrSum.argmin() // This will find the index of the minimum number inside an array.
# // arrSum.argmax() // This will find the index of the maximum number inside an array.

# // Quick & Simple rule:

# // maximum number = arrSum.max() && maximum number index = arrSum.argmax()
# // minimum number = arrSum.min() && maximum number index = arrSum.argmin()

# // Reshaping and resizing:

# // Reshaping is the process of converting an array from one dimension to another (like 1D → 2D or 2D → 3D)  without changing the values inside it. Reshaping means changing the shape (structure) of an array without changing its data.

# // Example:

# // arrTo30 = np.arange(1,31)

#    arrTo30 // output: array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
#        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

#    arrTo30 = arrTo30.reshape(3,10)
#    arrTo30  // output: array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
#        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

