In [ ]:
# Array Operations

# What we are gonna study in it:

# Arithmetic operations
# Broadcasting 
# Deep and Shallow Copy
# Matrix Operations
# Advance Array Manipulation 
# Stacking Array
# Spliting Array

In [4]:
import numpy as np 

array([1, 2, 3, 4, 5])

In [ ]:
# Arithmetic Operaations:

In [8]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

arrPlus = a1 + a2 # This will add the element like that way:
        # a1[0] + a2[0] , a1[1] + a2[1] , a1[2] + a2[3] and so on till end and after adding all this will 
        # provide a vector array
arrPlus
# Pro tip: Whenever you want to perform the array operation the size(index) of both arrays must be equal
# or other wise braodcasting error will come. 

array([ 7,  9, 11, 13, 15])

In [9]:
arrMinus = a1 - a2
arrMinus

array([-5, -5, -5, -5, -5])

In [10]:
arrMul = a1 * a2
arrMul

array([ 6, 14, 24, 36, 50])

In [11]:
arrDiv = a1 / a2
arrDiv

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [12]:
arrDivToNearestWholeNum = a1 // a2
arrDivToNearestWholeNum 

array([0, 0, 0, 0, 0])

In [13]:
arrExponent = a1 ** a2
arrExponent

array([      1,     128,    6561,  262144, 9765625])

In [ ]:
# Broadcasting:

In [14]:
# Broadcasting in NumPy is a powerful feature that lets you perform operations
# on arrays of different shapes without manually reshaping or looping.

#Example:

# Broadcasting with vector array: 

l = [10,20,30,40]
arr = np.array(l)
arr = arr + 10

arr

# Broadcasting allow you to perform arithmetic operation on a list by one specific given number

array([20, 30, 40, 50])

In [17]:
# Broadcasting with matrix array: 

arrBroadMatrix = np.arange(1,26).reshape(5,5)
arrBroadMatrix = arrBroadMatrix + 10

arrBroadMatrix


array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
# Deep and Shallow Copy:

In [20]:
# In NumPy, deep copy and shallow copy explain whether a new array is truly independent or still linked to the original.
# This is a very important concept because it controls whether changes affect original data or not.

a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [23]:
# This is shallow copy example:

slice = a[:5]
slice = slice * 10
slice 

array([10, 20, 30, 40, 50])

In [25]:
a[4:6] * 10

array([50, 60])

In [26]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [27]:
# This is deep copy example:
b = a
b[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [30]:
# if you want that the changes will not occur on a then we can say:a

b = a.copy()
b[0] = 100
a[0] = 1
a 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# Matrix Operations:

In [34]:
A = np.array([[1,2] , [3,4]])
B = np.array([[5,6] , [7,8]])

In [35]:
A

array([[1, 2],
       [3, 4]])

In [36]:
B

array([[5, 6],
       [7, 8]])

In [37]:
A * B

array([[ 5, 12],
       [21, 32]])

In [38]:
A @ B

array([[19, 22],
       [43, 50]])

In [45]:
C = np.array([[5,6] , [12,3]])
D = np.array([[9,2] , [9,17]])

In [46]:
C

array([[ 5,  6],
       [12,  3]])

In [47]:
D

array([[ 9,  2],
       [ 9, 17]])

In [50]:
# There's two way of finding matrix multiplication:
# one is:
C @ D
# second is:
np.dot(C,D)

array([[ 99, 112],
       [135,  75]])

In [54]:
# How to transpose a matrix array:

# The transpose of an array means Converting rows into columns and columns into rows.
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
# Advance Array Manipulation:

In [55]:
# Stacking Array:
A

array([[1, 2],
       [3, 4]])

In [56]:
B

array([[5, 6],
       [7, 8]])

In [59]:
# Tip: You cannot stack two matrix arrays only vectors can get stacked:A

# Types of stacks:
# Vertical stack
# Horizontal stack
# Simple stack

# Example of vertical stack:

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

resultvstack = np.vstack((a,b)) # vtack() fuction only takes one positional 
resultvstack



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [61]:
# Example of horizontal stack:

resulthstack = np.hstack((a,b))
resulthstack

array([1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
# Example of column stack:A

resultcstack = np.column_stack((a,b))
resultcstack

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# Splitting Arrays

In [65]:
c = np.arange(16).reshape(4,4)
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [66]:
np.hsplit(c,4)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [70]:
np.vsplit(c,4)

[array([[0, 1, 2, 3]]),
 array([[4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]