In [2]:
import numpy as np 

In [5]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],

    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],

    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])


In [15]:
# axis = 0 always targets columns a
b = np.sum(s,axis=1)
b == 45

for i in b :
    if i != 45 :
        print("Sudoku is not valid!!")
        break
else :
    print("For rows its valid!!")

For rows its valid!!


In [16]:
c = np.sum(s,axis=0)
c == 45

for i in b :
    if i != 45 :
        print("Sudoku is not valid!!")
        break
else :
    print("For column its valid!!")

For column its valid!!


In [17]:
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [24]:
# First method to check each three rows and column that sudoku is valid or not:

isudokuvalid = np.sum(s[:3 , :3]) and np.sum(s[3:6 , 3:6]) and np.sum(s[6: , 6:]) == 45
isudokuvalid

np.True_

In [29]:
# Second method to check that the 3 rows and 9 column are valid or not: 

issudokuvalid9 = np.sum(s[:3 , :]) == 135
issudokuvalid9

np.True_

In [39]:
# Numpy style :

for i in range(0,9,3) :
    for j in range(0,9,3) :
        n = s[i:i+3,j:j+3]
        print(n.sum())

45
45
45
45
45
45
45
45
45


In [48]:
# Column: [age , math marks , science marks] 
data = np.array([
    [18,85,78], #Student 1
    [19,92,88], #Student 2
    [17,76,95], #Student 3
    [18,65,70], #Student 4
    [20,90,85], #Student 5
])

In [47]:
# Get the shape of the matrix: 

data.shape

(5, 3)

In [52]:
# Find the average age of students:

np.mean(data[:,0])

np.float64(18.4)

In [55]:
# Extract maths marks of all students:

data[:,1]

array([85, 92, 76, 65, 90])

In [58]:
# Find the highest science marks: 

allScienceMarks = data[: , 2]
allScienceMarks.max()

np.int64(95)

In [61]:
# Get details of the students who score 90 plus in math exams:

bool_marks = data[:,1] >= 90 
bool_marks

array([False,  True, False, False,  True])

In [66]:
# Increase Math marks of all students by 5:

mathdata = data[:,1]
result = mathdata + 5 
result

array([100, 107,  91,  80, 105])

In [74]:
# Find how many students are younger than 19:

len(data[data[:,0] < 19])

3

In [79]:
# Calculate the average marks in each subject (column-wise): 

np.mean(data[:,1:] , axis=0)

array([91.6, 83.2])

In [80]:
# Get the max of the students who score atleast 80 marks in both subject: 

data[ (data[:,1] >= 80) & (data[:,2] >= 80) ] 

array([[ 19, 102,  88],
       [ 17,  86,  95],
       [ 20, 100,  85]])

In [94]:
# Replace all the marks < 75 to 0:

data[:2][data[:,2] < 75] = 0 
data

IndexError: boolean index did not match indexed array along axis 0; size of axis is 2 but size of corresponding boolean axis is 5