In [ ]:
# In this section we will learn:

# Numpy Indexing and Slicing of vectors
# Numpy Indexing and Slicing of matrix
# Boolean Indexing

In [3]:
import numpy as np

In [ ]:
# Numpy Indexing and Slicing of vectors:

In [5]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [6]:
# This is array "Indexing".
arr[6] # Simple formula of indexing and slicing is arr[start , stop , skip]

np.int64(17)

In [8]:
# This is array "Slicing" 

# Array slicing means removing specific index value from an array.abs

arr[:] # This colun means start from zero index and go till end

array([15, 16, 17, 18, 19, 20])

In [9]:
arr[:4] # This colun means start from zero and go till 4th

array([11, 12, 13, 14])

In [10]:
arr[4:] # This colun means start from 4th index and go till end

array([15, 16, 17, 18, 19, 20])

In [12]:
arr[0:5] # Array in numpy start from 0 index go until number of n and 
# when we say 0:5 start from zero and go till 5 but it will select select 0 from 4th element it will not go
# to 5th index it works like range function. 

# Simple rule:
# Select startingindex and endingIndex plus oneabs
# StartingIndex:EndingIndex+1  to get the exact ending index. 


array([12, 13, 14, 15])

In [13]:
arr[3::2] # Now the third value means how much index you want to skip. 

array([14, 16, 18, 20])

In [ ]:
# Numpy Indexing and Slicing of matrix

In [17]:
arrm = np.arange(1,31)
arrm = arrm.reshape(6,5)
arrm 

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [19]:
arrm[0] # The first value in matrix indexing will target rows

array([1, 2, 3, 4, 5])

In [20]:
arrm[5] 

array([26, 27, 28, 29, 30])

In [23]:
arrm[0,4] # Now this will get the 0 row and 5 column element.

np.int64(5)

In [24]:
arrm[5,4]

np.int64(30)

In [25]:
arrm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [26]:
arrm[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [28]:
arrm[3:, 3: ]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [30]:
arrm[4: , 1:3]

array([[22, 23],
       [27, 28]])

In [31]:
arrm

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [32]:
arrm[2:4 , 1:3]

array([[12, 13],
       [17, 18]])

In [ ]:
arrm[:,2] # If you want to slice a full colomn then you should say like that 

In [ ]:
# Boolean Indexing:

In [33]:
arrBoolean = np.arange(11,21)
arrBoolean

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
bool_index = arrBoolean % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [43]:
arrBoolean = arrBoolean[bool_index]
arrBoolean

IndexError: boolean index did not match indexed array along axis 0; size of axis is 5 but size of corresponding boolean axis is 10